"use client"

import { Link } from "next-view-transitions"
import { ArrowRight, Sparkles } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { cn } from "@/lib/utils"
import type { CheckInSession } from "@/lib/types"

interface InsightsPanelProps {
  session: CheckInSession | null
  className?: string
}

export function InsightsPanel({ session, className }: InsightsPanelProps) {
  const synthesis = session?.synthesis

  if (!session || !synthesis) {
    return (
      <Card className={cn("border-border/70 bg-card/30 backdrop-blur-xl", className)}>
        <CardHeader>
          <CardTitle className="text-sm flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-accent" />
            Insights
          </CardTitle>
          <CardDescription>
            Finish a check-in to get an evidence-backed synthesis from Gemini 3.
          </CardDescription>
        </CardHeader>
      </Card>
    )
  }

  return (
    <Card className={cn("border-border/70 bg-card/30 backdrop-blur-xl", className)}>
      <CardHeader className="flex-row items-start justify-between gap-3">
        <div>
          <CardTitle className="text-sm flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-accent" />
            Insights
          </CardTitle>
          <CardDescription>
            From your latest check-in • Generated by Gemini 3
          </CardDescription>
        </div>
        <Badge variant="secondary" className="shrink-0">
          {synthesis.insights.length} insights
        </Badge>
      </CardHeader>

      <CardContent className="space-y-3">
        <p className="text-sm text-muted-foreground">{synthesis.narrative}</p>

        <div className="space-y-2">
          {synthesis.insights.map((insight) => (
            <div key={insight.id} className="rounded-lg border border-border/50 bg-background/30 p-3">
              <p className="text-sm font-medium leading-snug">{insight.title}</p>
              <p className="text-xs text-muted-foreground mt-1">{insight.description}</p>
              {insight.evidence.quotes[0]?.text ? (
                <p className="text-xs text-muted-foreground mt-2 border-l-2 border-border pl-3">
                  “{insight.evidence.quotes[0].text}”
                </p>
              ) : null}
            </div>
          ))}
        </div>

        <Button asChild variant="outline" size="sm" className="w-full gap-2">
          <Link href={`/dashboard/history?highlight=${session.id}`}>
            View full check-in
            <ArrowRight className="h-4 w-4 ml-auto" />
          </Link>
        </Button>
      </CardContent>
    </Card>
  )
}

