"use client"

import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Sparkles } from "@/lib/icons"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { cn } from "@/lib/utils"
import { Deck } from "@/components/dashboard/deck"
import type { CheckInSession } from "@/lib/types"

interface InsightsPanelProps {
  session: CheckInSession | null
  className?: string
}

export function InsightsPanel({ session, className }: InsightsPanelProps) {
  const synthesis = session?.synthesis

  if (!session || !synthesis) {
    return (
      <Deck className={cn("p-6", className)}>
        <div className="flex items-start justify-between gap-3">
          <div>
            <div className="text-sm font-medium flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-accent" />
              Insights
            </div>
            <p className="text-sm text-muted-foreground mt-1">
              <span className="inline-flex items-center gap-1">
                Finish a check-in to get an evidence-backed synthesis from Gemini 3.
                <Image src="/gemini-logo.svg" alt="Gemini" width={14} height={14} />
              </span>
            </p>
          </div>
        </div>
      </Deck>
    )
  }

  return (
    <Deck className={cn("p-6", className)}>
      <div className="flex items-start justify-between gap-3">
        <div>
          <div className="text-sm font-medium flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-accent" />
            Insights
          </div>
          <p className="text-sm text-muted-foreground mt-1">
            <span className="inline-flex items-center gap-1">
              From your latest check-in • Generated by Gemini 3
              <Image src="/gemini-logo.svg" alt="Gemini" width={14} height={14} />
            </span>
          </p>
        </div>
        <Badge variant="secondary" className="shrink-0">
          {synthesis.insights.length} insights
        </Badge>
      </div>

      <div className="mt-4 space-y-3">
        <p className="text-sm text-muted-foreground">{synthesis.narrative}</p>

        <div className="space-y-2">
          {synthesis.insights.map((insight) => (
            <div key={insight.id} className="rounded-lg border border-border/50 bg-background/40 p-3">
              <p className="text-sm font-medium leading-snug">{insight.title}</p>
              <p className="text-xs text-muted-foreground mt-1">{insight.description}</p>
              {insight.evidence.quotes[0]?.text ? (
                <p className="text-xs text-muted-foreground mt-2 border-l-2 border-border pl-3">
                  “{insight.evidence.quotes[0].text}”
                </p>
              ) : null}
            </div>
          ))}
        </div>

        <Button asChild variant="outline" size="sm" className="w-full gap-2">
          <Link href={`/check-ins?highlight=${session.id}`}>
            View full check-in
            <ArrowRight className="h-4 w-4 ml-auto" />
          </Link>
        </Button>
      </div>
    </Deck>
  )
}
