import type { ComponentType, SVGProps } from "react"

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>
export type LucideIcon = IconComponent

export { WarningCircle as AlertCircle } from "iconoir-react"
export { WarningTriangle as AlertTriangle } from "iconoir-react"
export { ArrowLeft } from "iconoir-react"
export { ArrowRight } from "iconoir-react"
export { ArrowUpRight } from "iconoir-react"
export { Bell } from "iconoir-react"
export { Book as BookOpen } from "iconoir-react"
export { Brain } from "iconoir-react"
export { Calendar } from "iconoir-react"
export { CalendarCheck } from "iconoir-react"
export { CalendarPlus } from "iconoir-react"
export { CalendarXmark as CalendarX } from "iconoir-react"
export { Check } from "iconoir-react"
export { CheckCircle as CheckCircle2 } from "iconoir-react"
export { Check as CheckIcon } from "iconoir-react"
export { CheckSquare } from "iconoir-react"
export { NavArrowDown as ChevronDown } from "iconoir-react"
export { NavArrowDown as ChevronDownIcon } from "iconoir-react"
export { NavArrowLeft as ChevronLeft } from "iconoir-react"
export { NavArrowLeft as ChevronLeftIcon } from "iconoir-react"
export { NavArrowRight as ChevronRight } from "iconoir-react"
export { NavArrowRight as ChevronRightIcon } from "iconoir-react"
export { NavArrowUp as ChevronUp } from "iconoir-react"
export { NavArrowUp as ChevronUpIcon } from "iconoir-react"
export { Sort as ChevronsUpDown } from "iconoir-react"
export { Circle as CircleIcon } from "iconoir-react"
export { Clock } from "iconoir-react"
export { CoffeeCup as Coffee } from "iconoir-react"
export { Gym as Dumbbell } from "iconoir-react"
export { OpenNewWindow as ExternalLink } from "iconoir-react"
export { Eye } from "iconoir-react"
export { EyeClosed as EyeOff } from "iconoir-react"
export { Filter } from "iconoir-react"
export { Bonfire as Flame } from "iconoir-react"
export { DashboardSpeed as Gauge } from "iconoir-react"
export { Globe as Globe2 } from "iconoir-react"
export { DragHandGesture as GripVertical } from "iconoir-react"
export { DragHandGesture as GripVerticalIcon } from "iconoir-react"
export { Heart } from "iconoir-react"
export { MailIn as Inbox } from "iconoir-react"
export { InfoCircle as Info } from "iconoir-react"
export { Key } from "iconoir-react"
export { MultiplePages as Layers } from "iconoir-react"
export { Refresh as Loader2 } from "iconoir-react"
export { Refresh as Loader2Icon } from "iconoir-react"
export { Menu } from "iconoir-react"
export { ChatBubble as MessageCircle } from "iconoir-react"
export { MessageText as MessageSquare } from "iconoir-react"
export { Microphone as Mic } from "iconoir-react"
export { MicrophoneMute as MicOff } from "iconoir-react"
export { Minus } from "iconoir-react"
export { Minus as MinusIcon } from "iconoir-react"
export { HalfMoon as Moon } from "iconoir-react"
export { MoreHoriz as MoreHorizontal } from "iconoir-react"
export { MoreHoriz as MoreHorizontalIcon } from "iconoir-react"
export { Journal as NotebookPen } from "iconoir-react"
export { ColorPicker as Paintbrush } from "iconoir-react"
export { Palette } from "iconoir-react"
export { SidebarCollapse as PanelLeftIcon } from "iconoir-react"
export { Pause } from "iconoir-react"
export { PhoneDisabled as PhoneOff } from "iconoir-react"
export { Play } from "iconoir-react"
export { Plus } from "iconoir-react"
export { RefreshDouble as RefreshCw } from "iconoir-react"
export { Undo as RotateCcw } from "iconoir-react"
export { Search as SearchIcon } from "iconoir-react"
export { Send } from "iconoir-react"
export { Settings } from "iconoir-react"
export { Shield } from "iconoir-react"
export { Sparks as Sparkles } from "iconoir-react"
export { Square } from "iconoir-react"
export { Compass as Target } from "iconoir-react"
export { ThumbsDown } from "iconoir-react"
export { ThumbsUp } from "iconoir-react"
export { Refresh as TimerReset } from "iconoir-react"
export { Trash as Trash2 } from "iconoir-react"
export { GraphDown as TrendingDown } from "iconoir-react"
export { GraphUp as TrendingUp } from "iconoir-react"
export { Trophy } from "iconoir-react"
export { User } from "iconoir-react"
export { Group as Users } from "iconoir-react"
export { SoundHigh as Volume2 } from "iconoir-react"
export { SoundOff as VolumeX } from "iconoir-react"
export { Wind } from "iconoir-react"
export { Xmark as X } from "iconoir-react"
export { XmarkCircle as XCircle } from "iconoir-react"
export { Xmark as XIcon } from "iconoir-react"
export { Flash as Zap } from "iconoir-react"

