import { Temporal } from "temporal-polyfill"
import type { Suggestion } from "@/lib/types"

export const LAST_SUGGESTION_ROLLOVER_DATE_KEY = "kanari:suggestions:lastRolloverDate"
export const LAST_SUGGESTION_AUTOGEN_DATE_KEY = "kanari:suggestions:lastAutoGeneratedDate"

export function toLocalDateISO(iso: string, timeZone: string): string | null {
  try {
    return Temporal.Instant.from(iso).toZonedDateTimeISO(timeZone).toPlainDate().toString()
  } catch {
    return null
  }
}

export function getTodayISO(timeZone: string, nowISO: string): string {
  const local = toLocalDateISO(nowISO, timeZone)
  return local ?? Temporal.Now.plainDateISO().toString()
}

export function computeExpiredSuggestionIds({
  suggestions,
  timeZone,
  nowISO,
}: {
  suggestions: Suggestion[]
  timeZone: string
  nowISO: string
}): {
  todayISO: string
  expiredSuggestionIds: string[]
} {
  const todayISO = getTodayISO(timeZone, nowISO)

  const expiredSuggestionIds: string[] = []

  for (const suggestion of suggestions) {
    if (suggestion.status === "completed" || suggestion.status === "accepted" || suggestion.status === "dismissed") {
      continue
    }

    const reference = suggestion.status === "scheduled"
      ? suggestion.scheduledFor ?? suggestion.createdAt
      : suggestion.createdAt

    const suggestionDay = toLocalDateISO(reference, timeZone)
    if (!suggestionDay) continue

    // Anything not completed by end-of-day should not carry forward.
    if (suggestionDay < todayISO) {
      expiredSuggestionIds.push(suggestion.id)
    }
  }

  return { todayISO, expiredSuggestionIds }
}

export function normalizeSuggestionKey(input: { content: string; category: string; duration: number }): string {
  const content = input.content
    .toLowerCase()
    .replace(/\s+/g, " ")
    .replace(/[\u2019']/g, "'")
    .trim()
  return `${input.category}|${input.duration}|${content}`
}
