/**
 * Achievement System Types
 *
 * Defines types for the dynamic AI-generated achievements system.
 * Unlike traditional hardcoded badges, achievements are personalized by Gemini
 * based on user patterns and journey.
 */

/**
 * Achievement category - determines the icon and color scheme
 */
export type AchievementCategory =
  | "streak"        // Consistency achievements (daily check-ins, streaks)
  | "milestone"     // Milestone achievements (first recording, 10 recordings)
  | "improvement"   // Improvement achievements (stress reduction, better sleep)
  | "engagement"    // Engagement achievements (trying different suggestion types)
  | "pattern"       // Pattern recognition achievements (morning person, night owl)
  | "recovery"      // Recovery achievements (completing recovery activities)

/**
 * Achievement rarity level - affects visual styling
 */
export type AchievementRarity = "common" | "uncommon" | "rare" | "epic" | "legendary"

/**
 * A single achievement generated by Gemini
 */
export interface Achievement {
  /** Unique identifier */
  id: string
  /** Short, catchy title (e.g., "Monday Mood Master") */
  title: string
  /** Longer description explaining why they earned it */
  description: string
  /** Category for icon/color selection */
  category: AchievementCategory
  /** Rarity level for visual distinction */
  rarity: AchievementRarity
  /** When this achievement was earned */
  earnedAt: string
  /** The specific insight that triggered this achievement */
  insight: string
  /** Optional: emoji to display with the achievement */
  emoji?: string
}

/**
 * User stats sent to Gemini for achievement generation
 * These stats help Gemini understand the user's journey
 */
export interface UserStatsForAchievements {
  // Recording stats
  totalRecordings: number
  recordingsThisWeek: number
  recordingStreak: number // Consecutive days with recordings
  longestStreak: number

  // Time patterns
  preferredTimeOfDay: "morning" | "afternoon" | "evening" | "night" | "varied"
  mostActiveDay: string // e.g., "Monday"

  // Stress & fatigue trends
  averageStressScore: number
  averageFatigueScore: number
  stressTrend: "improving" | "stable" | "worsening"
  fatigueTrend: "improving" | "stable" | "worsening"
  lowestStressDay: string | null
  highestImprovementDay: string | null

  // Suggestion engagement
  suggestionsCompleted: number
  suggestionsScheduled: number
  suggestionsDismissed: number
  favoriteCategory: string | null // Most completed category
  leastUsedCategory: string | null
  completionRate: number // Percentage of accepted suggestions completed

  // Effectiveness feedback (from the feature we just built)
  helpfulSuggestionsCount: number
  totalFeedbackGiven: number

  // Check-in sessions
  totalCheckInSessions: number
  averageSessionDuration: number // seconds

  // Milestones
  daysActive: number // Total unique days with activity
  firstRecordingDate: string | null

  // Recent achievements (to avoid duplicates)
  recentAchievementTitles: string[]

  // Data quality indicators (help Gemini assess if there's enough data for meaningful achievements)
  dataQuality: {
    /** Days since first recording */
    journeyDurationDays: number
    /** True if user has 14+ days of history */
    hasEnoughHistory: boolean
    /** True if user was active on 50%+ of days since starting */
    hasConsistentUsage: boolean
    /** True if there's enough variance in metrics to detect real trends */
    hasMeasurableTrends: boolean
    /** Percentage of suggestions user interacted with (not left pending) */
    suggestionEngagementRate: number
  }
}

/**
 * Gemini's response when generating achievements
 */
export interface GeminiAchievementResponse {
  achievements: Array<{
    title: string
    description: string
    category: AchievementCategory
    rarity: AchievementRarity
    insight: string
    emoji: string
  }>
  /** Explanation of why these achievements were chosen */
  reasoning: string
}

/**
 * Stored achievement with metadata
 */
export interface StoredAchievement extends Achievement {
  /** Whether the user has seen/acknowledged this achievement */
  seen: boolean
  /** When the user saw this achievement (for animation timing) */
  seenAt?: string
}

/**
 * Achievement notification for toast/celebration
 */
export interface AchievementNotification {
  achievement: Achievement
  isNew: boolean
}
