"use client"

import { useMemo } from "react"
import Image from "next/image"
import { RefreshCw, ArrowRight } from "@/lib/icons"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import type { CheckInSession, CheckInSynthesis } from "@/lib/types"
import { BiomarkerIndicator } from "@/components/check-in/biomarker-indicator"
import { formatDate } from "@/lib/date-utils"
import { useTimeZone } from "@/lib/timezone-context"

interface SynthesisScreenProps {
  session: CheckInSession | null
  synthesis: CheckInSynthesis | null
  isLoading: boolean
  error?: string | null
  onRetry?: () => void
  onViewDashboard?: () => void
  onDone?: () => void
  className?: string
}

export function SynthesisScreen({
  session,
  synthesis,
  isLoading,
  error,
  onRetry,
  onViewDashboard,
  onDone,
  className,
}: SynthesisScreenProps) {
  const { timeZone } = useTimeZone()
  const insightTitleById = useMemo(() => {
    const map = new Map<string, string>()
    for (const insight of synthesis?.insights ?? []) {
      map.set(insight.id, insight.title)
    }
    return map
  }, [synthesis])

  return (
    <div className={cn("flex-1 flex flex-col overflow-hidden", className)}>
      <div className="flex-1 overflow-auto px-6 py-6">
        <div className="mx-auto w-full max-w-2xl space-y-4">
          {/* Header */}
          <div className="flex items-start justify-between gap-3">
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <div className="h-9 w-9 rounded-full bg-accent/10 flex items-center justify-center">
                  <Image src="/gemini-logo.svg" alt="Gemini" width={20} height={20} />
                </div>
                <div className="min-w-0">
                  <p className="text-base font-semibold leading-tight">Check-in synthesis</p>
                  <p className="text-xs text-muted-foreground">
                    <span className="inline-flex items-center gap-1">
                      Generated by Gemini 3{session?.endedAt ? ` • ${formatDate(session.endedAt, timeZone)}` : ""}
                      <Image src="/gemini-logo.svg" alt="Gemini" width={14} height={14} />
                    </span>
                  </p>
                </div>
              </div>
            </div>

            {synthesis?.meta?.input ? (
              <Badge variant="secondary" className="shrink-0">
                {synthesis.meta.input.messagesUsed}/{synthesis.meta.input.messagesTotal} msgs
                {synthesis.meta.input.truncated ? " • trimmed" : ""}
              </Badge>
            ) : null}
          </div>

          {/* Biomarkers (quick continuity cue) */}
          {session ? (
            <div className="rounded-lg border border-border/70 bg-card/30 backdrop-blur-xl p-4">
              <p className="text-xs font-medium text-muted-foreground mb-2">Voice biomarkers (this check-in)</p>
              {session.acousticMetrics ? (
                <BiomarkerIndicator metrics={session.acousticMetrics} compact />
              ) : (
                <p className="text-xs text-muted-foreground">
                  Not enough speech captured to analyze stress/fatigue. Try speaking for about 1-2 seconds next time.
                </p>
              )}
            </div>
          ) : null}

          {/* Loading */}
          {isLoading && (
            <Card className="border-border/70 bg-card/30 backdrop-blur-xl">
              <CardHeader>
                <CardTitle className="text-sm flex items-center gap-2">
                  <RefreshCw className="h-4 w-4 animate-spin text-muted-foreground" />
                  Synthesizing your check-in…
                </CardTitle>
                <CardDescription>
                  Kanari is asking Gemini 3 to connect your conversation, journal, and voice patterns into a clear “why”.
                </CardDescription>
              </CardHeader>
            </Card>
          )}

          {/* Error */}
          {!isLoading && error && (
            <Card className="border-border/70 bg-card/30 backdrop-blur-xl">
              <CardHeader>
                <CardTitle className="text-sm">Synthesis unavailable</CardTitle>
                <CardDescription className="break-words">{error}</CardDescription>
              </CardHeader>
              <CardContent className="flex gap-2">
                {onRetry ? (
                  <Button variant="outline" onClick={onRetry}>
                    Retry
                  </Button>
                ) : null}
                {onDone ? <Button onClick={onDone}>Done</Button> : null}
              </CardContent>
            </Card>
          )}

          {/* Synthesis content */}
          {!isLoading && !error && synthesis && (
            <>
              <Card className="border-border/70 bg-card/30 backdrop-blur-xl">
                <CardHeader>
                  <CardTitle className="text-sm">Narrative</CardTitle>
                  <CardDescription>{synthesis.narrative}</CardDescription>
                </CardHeader>
              </Card>

              <div className="space-y-3">
                <p className="text-sm font-medium">Key insights (with evidence)</p>
                {synthesis.insights.map((insight) => (
                  <Card
                    key={insight.id}
                    className="border-border/70 bg-card/30 backdrop-blur-xl"
                  >
                    <CardHeader>
                      <CardTitle className="text-sm">{insight.title}</CardTitle>
                      <CardDescription>{insight.description}</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-3">
                      {insight.evidence.quotes.length > 0 && (
                        <div className="space-y-2">
                          <p className="text-xs font-medium text-muted-foreground">Quotes</p>
                          <div className="space-y-2">
                            {insight.evidence.quotes.map((q, idx) => (
                              <blockquote
                                key={`${insight.id}-q-${idx}`}
                                className="border-l-2 border-border pl-3 text-sm text-muted-foreground"
                              >
                                <span className="font-medium capitalize text-foreground/80">{q.role}:</span>{" "}
                                “{q.text}”
                              </blockquote>
                            ))}
                          </div>
                        </div>
                      )}

                      {(insight.evidence.voice.length > 0 || insight.evidence.journal.length > 0) && (
                        <div className="grid gap-3 sm:grid-cols-2">
                          {insight.evidence.voice.length > 0 && (
                            <div className="space-y-1">
                              <p className="text-xs font-medium text-muted-foreground">Voice patterns</p>
                              <ul className="text-xs text-muted-foreground list-disc pl-4 space-y-1">
                                {insight.evidence.voice.map((v, idx) => (
                                  <li key={`${insight.id}-v-${idx}`}>{v}</li>
                                ))}
                              </ul>
                            </div>
                          )}
                          {insight.evidence.journal.length > 0 && (
                            <div className="space-y-1">
                              <p className="text-xs font-medium text-muted-foreground">Journal</p>
                              <ul className="text-xs text-muted-foreground list-disc pl-4 space-y-1">
                                {insight.evidence.journal.map((j, idx) => (
                                  <li key={`${insight.id}-j-${idx}`}>{j}</li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>
                      )}
                    </CardContent>
                  </Card>
                ))}
              </div>

              <div className="space-y-3">
                <p className="text-sm font-medium">Targeted suggestions (with “why”)</p>
                {synthesis.suggestions.map((suggestion) => (
                  <Card
                    key={suggestion.id}
                    className="border-border/70 bg-card/30 backdrop-blur-xl"
                  >
                    <CardHeader>
                      <CardTitle className="text-sm leading-snug">{suggestion.content}</CardTitle>
                      <CardDescription>{suggestion.rationale}</CardDescription>
                    </CardHeader>
                    {suggestion.linkedInsightIds.length > 0 && (
                      <CardContent>
                        <p className="text-xs font-medium text-muted-foreground mb-2">Linked insights</p>
                        <div className="flex flex-wrap gap-2">
                          {suggestion.linkedInsightIds.map((id) => (
                            <Badge key={`${suggestion.id}-${id}`} variant="secondary">
                              {insightTitleById.get(id) ?? "Insight"}
                            </Badge>
                          ))}
                        </div>
                      </CardContent>
                    )}
                  </Card>
                ))}
              </div>
            </>
          )}
        </div>
      </div>

      {/* Footer actions */}
      <div className="flex-shrink-0 border-t border-border/70 bg-background/60 backdrop-blur px-6 py-4">
        <div className="mx-auto w-full max-w-2xl flex items-center justify-between gap-2">
          {onDone ? (
            <Button variant="outline" onClick={onDone}>
              Done
            </Button>
          ) : (
            <span />
          )}
          {onViewDashboard ? (
            <Button onClick={onViewDashboard} className="gap-2">
              View on Dashboard
              <ArrowRight className="h-4 w-4" />
            </Button>
          ) : null}
        </div>
      </div>
    </div>
  )
}
